# Generated by Django 5.0.6 on 2024-07-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_speciality_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('internal_medicine', 'терапевт'), ('pediatrics', 'педиатр'), ('surgery', 'хирург'), ('cardiology', 'кардиолог'), ('neurology', 'невролог'), ('ophthalmology', 'офтальмолог')], max_length=150, null=True, verbose_name='специальность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужчина'), ('female', 'женщина'), ('other', 'другое')], max_length=15, null=True, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/', verbose_name='фото'),
        ),
    ]
