# Generated by Django 5.0.6 on 2024-08-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasehistory',
            old_name='Nurse',
            new_name='nurse',
        ),
        migrations.AddField(
            model_name='diseasehistory',
            name='complaints',
            field=models.TextField(default='', verbose_name='жалобы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcard',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
